base_url = "https://Pikman1210.github.io/"
title = "Pikman1210's Site"
description = "This is an example description"
build_search_index = true
generate_feeds = true
compile_sass = true
minify_html = true
taxonomies = [{ name = "tags" }]

# Theme Choice
theme = "apollo"

[markdown]
# Whether to do syntax highlighting
# Theme can be customised by setting the `highlight_theme` variable to a theme supported by Zola
highlight_code = true

[extra]
toc = true
use_cdn = false
favicon = "/icon/favicon.png"
theme = "toggle" # light, dark, auto, toggle
comment = false
fancy_code = true
dynamic_note = true           # a note that can be toggled
mathjax = true
mathjax_dollar_inline_enable = true
repo_url = "https://github.com/Pikman1210/Pikman1210.github.io/tree/main/content"

menu = [
    { name = "About", url = "/about", weight = 1 },
    { name = "Posts", url = "/posts", weight = 2 },
    { name = "Projects", url = "/projects", weight = 3 },
    { name = "Tags", url = "/tags", weight = 4 },
]
socials = [
    { name = "youtube", url = "https://www.youtube.com/@pikman1210", icon = "youtube" },
    { name = "twitch", url = "https://www.twitch.tv/pikman1210", icon = "twitch" },
    { name = "github", url = "https://github.com/pikman1210/", icon = "github" },
]

custom_css = []

[extra.analytics]
enabled = false