base_url = "https://Pikman1210.github.io/"
title = "not-matthias"
description = "This is an example description"
build_search_index = true
generate_feeds = true
compile_sass = true
minify_html = true
taxonomies = [{ name = "tags" }]

# Theme Choice
theme = "apollo"

[markdown]
# Whether to do syntax highlighting
# Theme can be customised by setting the `highlight_theme` variable to a theme supported by Zola
highlight_code = true

[extra]
toc = true
use_cdn = false
favicon = "/icon/favicon.png"
theme = "dark" # light, dark, auto, toggle
comment = false
fancy_code = true
dynamic_note = true           # a note that can be toggled
mathjax = true
mathjax_dollar_inline_enable = true
repo_url = "https://github.com/not-matthias/apollo/tree/main/content"

menu = [
  # Configure menu bar here
]
socials = [
    { name = "youtube", url = "https://www.youtube.com/@pikman1210", icon = "youtube" },
    { name = "github", url = "https://github.com/pikman1210/", icon = "github" },
]

custom_css = []

[extra.analytics]
enabled = false